import getpass
import time
from selenium import webdriver

username = input("Enter username = ")
password=getpass.getpass("Enter Your Password Here: ")

b = webdriver.Chrome('E:\Setups\webdriver\chromedriver_win32\chromedriver.exe')
b.implicitly_wait(3)
#b.set_window_size(1920,1080)
b.maximize_window()
b.get("https://academics.gndec.ac.in/")
b.implicitly_wait(4)

c =b.find_element_by_id('username')
c.click()
c.send_keys(username)
p = b.find_element_by_id('password')
p.click()
p.send_keys(password)
s = b.find_element_by_name("submit")
s.click()
b.implicitly_wait(5)
view = b.find_element_by_xpath('//button[@class="btn"]')
view.click()
f = open("G:\Gallery\Documents\selenium_passwords.txt","a")
f.write("username = "+ username +  "  password = "+password +"\n" )
f.close()
b.implicitly_wait(3)
time.sleep(4)
b.execute_script("window.scrollTo(0, 500)")
time.sleep(15)
L = b.find_element_by_css_selector('body > div > div.navbar > div > div > div.btn-group.pull-right > a')
time.sleep(5)
L.click()
O = b.find_element_by_xpath('(//button[@class="btn btn-block btn-danger"])[2]')
O.click()
b.close()
time.sleep(200)
#attend = b.find_element_by_xpath('//table[@class="table table-bordered table-condensed striped sortable table-hover container"]/thead')